# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicDepartment', models.CharField(max_length=100)),
                ('calendarId', models.CharField(max_length=250)),
                ('firstName', models.CharField(max_length=100)),
                ('bsuir_id', models.IntegerField()),
                ('lastName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('photoLink', models.URLField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
