# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='publications',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
