# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='publications',
            new_name='images',
        ),
    ]
