# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('employees', '0003_auto_20170402_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='_memes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
