# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170404_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='raw_schedule',
            field=models.TextField(blank=True),
        ),
    ]
